org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# IDs y direcciones PÚBLICOS (van dentro de la app). Los secretos (llave de firma) NO van aquí.
GOOGLE_WEB_CLIENT_ID=122171626511-bfkne9bvlog80da1pk2i3rv4m8sptm3g.apps.googleusercontent.com
